---

- name: "include find the according files"
  include_tasks: "find.yml"
  vars:
    ansible_become: false

- name: "build files' list"
  copydata_buildfilelist:
    merge: "{{ copydata_copy_type }}"
    debug: "{{ copydata_debug }}"
    find_list:
      - "{{ _copydata_filelist_tmp_host }}"
      - "{{ _copydata_filelist_tmp_gp }}"
      - "{{ _copydata_filelist_tmp_all }}"
  register: _copydata_filelist_tmp

- name: "DEBUG > Result"
  debug:
    var: "{{ item }}"
  loop:
    - _copydata_filelist_tmp.meta.filenames
    - _copydata_filelist_tmp.meta.sources
  when: copydata_debug

- name: "remove other files if copydata_remove_other_files"
  include_tasks: "remove_other_files.yml"
  when: copydata_remove_other_files

- name: "copy files if copydata_copy_type == copy"
  include_tasks: "copy_files.yml"
  when: copydata_copy_type == "copy"

- name: "append files if copydata_copy_type in [append,append_reverse]"
  include_tasks: "append_files.yml"
  when: copydata_copy_type in ["append","append_reverse"]
