---
- name: "Find old files"
  find:
    path: "{{ copydata_dest }}"
    patterns: "{{ copydata_patterns }}"
    excludes: "{{ _copydata_filelist_tmp['meta']['filenames'] }}"
  register: _copydata_oldfiles

- name: "Remove old files"
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ _copydata_oldfiles.files }}"
  loop_control:
    label: "{{ item.path }}"
  register: _copydata_result_remove
