# step_id: id of the step
# item : filename
- name: "Verify {{ step_id }} - absents"
  stat:
    path: "/tmp/step{{ step_id }}/{{ item }}"
  loop: "{{ f }}"
  register: stat_result
  failed_when: stat_result.stat.exists|default()
