---
- name: Converge
  hosts: all
  tasks:
    - name: "Converge append_reverse 1 default"
      include_role:
        name: "ansible-copydata"
      vars:
        copydata_datadir: "{{ data_dir }}"
        copydata_src: 'default/'
        copydata_dest: "/tmp/step1/"
        copydata_owner: 'root'
        copydata_group: 'root'
        copydata_mode: '770'
        copydata_copy_type: "append_reverse"
      when: molecule_step|default('1') == '1'
    # -----------------------------------------------------
    - name: "Converge append_reverse 2 path exists"
      include_role:
        name: "ansible-copydata"
      vars:
        copydata_datadir: "{{ data_dir }}"
        copydata_src: 'default/'
        copydata_dest: "/tmp/step2/"
        copydata_owner: 'root'
        copydata_group: 'root'
        copydata_mode: '770'
        copydata_copy_type: "append_reverse"
      when: molecule_step|default('2') == '2'
    # -----------------------------------------------------
    - name: "Converge append_reverse 3 remove"
      include_role:
        name: "ansible-copydata"
      vars:
        copydata_datadir: "{{ data_dir }}"
        copydata_src: 'default/'
        copydata_dest: "/tmp/step3/"
        copydata_owner: 'root'
        copydata_group: 'root'
        copydata_mode: '770'
        copydata_copy_type: "append_reverse"
        copydata_remove_other_files: True
      when: molecule_step|default('3') == '3'
    # -----------------------------------------------------
    - name: "Converge append_reverse 4 pattern"
      include_role:
        name: "ansible-copydata"
      vars:
        copydata_datadir: "{{ data_dir }}"
        copydata_src: 'default/'
        copydata_dest: "/tmp/step4/"
        copydata_owner: 'root'
        copydata_group: 'root'
        copydata_mode: '770'
        copydata_copy_type: "append_reverse"
        copydata_patterns: "*host1.dummy"
      when: molecule_step|default('4') == '4'
    # -----------------------------------------------------
    - name: "Converge append_reverse 5 remove pattern"
      include_role:
        name: "ansible-copydata"
      vars:
        copydata_datadir: "{{ data_dir }}"
        copydata_src: 'default/'
        copydata_dest: "/tmp/step5/"
        copydata_owner: 'root'
        copydata_group: 'root'
        copydata_mode: '770'
        copydata_copy_type: "append_reverse"
        copydata_patterns:
          - "*host1.dummy"
          - "other_file.dummy"
        copydata_remove_other_files: True
      when: molecule_step|default('5') == '5'