---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: "Verify copy 1 default"
      include_tasks: ../_common/verify_item_exists.yml
      vars:
        step_id: 1
        f:
          - path: "onlyhost1.dummy"
            contains: |
              [comme from host1]
          - path: "host1.dummy"
            contains: |
              [comme from host1]
          - path: "gp2.dummy"
            contains: |
              [comme from gp2]
          - path: "gp1.dummy"
            contains: |
              [comme from gp1]
          - path: "all.dummy"
            contains: |
              [comme from all]
      when: molecule_step|default('1') == '1'
    # -----------------------------------------------------
    - name: "Verify copy 2 path exists"
      include_tasks: ../_common/verify_item_exists.yml
      vars:
        step_id: 2
        f:
          - path: "onlyhost1.dummy"
            contains: |
              [comme from host1]
          - path: "host1.dummy"
            contains: |
              [comme from host1]
          - path: "gp2.dummy"
            contains: |
              [comme from gp2]
          - path: "gp1.dummy"
            contains: |
              [comme from gp1]
          - path: "all.dummy"
            contains: |
              [comme from all]
          - path: "other_file"
            contains: |
              [already exists before test]
      when: molecule_step|default('2') == '2'
    # -----------------------------------------------------
    - name: "Verify copy 3 remove"
      include_tasks: ../_common/verify_item_exists.yml
      vars:
        step_id: 3
        f:
          - path: "onlyhost1.dummy"
            contains: |
              [comme from host1]
          - path: "host1.dummy"
            contains: |
              [comme from host1]
          - path: "gp2.dummy"
            contains: |
              [comme from gp2]
          - path: "gp1.dummy"
            contains: |
              [comme from gp1]
          - path: "all.dummy"
            contains: |
              [comme from all]
      when: molecule_step|default('3') == '3'

    - include_tasks: ../_common/verify_item_absents.yml
      vars:
        step_id: 3
        f:
          - "other_file"
          - "other_file.dummy"
      when: molecule_step|default('3') == '3'
    # -----------------------------------------------------
    - name: "Verify copy 4 pattern"
      include_tasks: ../_common/verify_item_exists.yml
      vars:
        step_id: 4
        f:
          - path: "onlyhost1.dummy"
            contains: |
              [comme from host1]
          - path: "host1.dummy"
            contains: |
              [comme from host1]
          - path: "other_file.dummy"
            contains: |
              [already exists before test]
          - path: "other_file"
            contains: |
              [already exists before test]
      when: molecule_step|default('4') == '4'

    - include_tasks: ../_common/verify_item_absents.yml
      vars:
        step_id: 4
        f:
        - "gp2.dummy"
        - "gp1.dummy"
        - "all.dummy"
      when: molecule_step|default('4') == '4'
    # -----------------------------------------------------
    - name: "Verify copy 5 remove pattern"
      include_tasks: ../_common/verify_item_exists.yml
      vars:
        step_id: 5
        f:
          - path: "onlyhost1.dummy"
            contains: |
              [comme from host1]
          - path: "host1.dummy"
            contains: |
              [comme from host1]
          # not removed because not in pattern
          - path: "other_file"
            contains: |
              [already exists before test]
      when: molecule_step|default('5') == '5'

    - include_tasks: ../_common/verify_item_absents.yml
      vars:
        step_id: 5
        f:
        - "gp2.dummy"
        - "gp1.dummy"
        - "all.dummy"
        - "other_file.dummy"
      when: molecule_step|default('5') == '5'
    # -----------------------------------------------------
    - name: "Verify copy 6 become"
      include_tasks: ../_common/verify_item_exists.yml
      vars:
        step_id: 6
        f:
          - path: "onlyhost1.dummy"
            contains: |
              [comme from host1]
          - path: "host1.dummy"
            contains: |
              [comme from host1]
      when: molecule_step|default('6') == '6'